name: gerenciador_contatos
description: Um aplicativo para gerenciar contatos com Flutter.
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  build_runner: ^2.1.0  # Necessário para gerar mocks

flutter:
  uses-material-design: true
